### ISSUE TITLE
Error Internal Service Error

### ISSUE THREAD

**Issue by controllinghand** [greymass/eos-voter#133]
Ok I think this is more user error than anything.  However, as a suggestion the errors should be more descriptive.  You need to have stake to send tokens and one more other error is if you use uppercase letters in the account name you will get an error.  Something to check for as well if you want this wallet to be more user friendly.

Thanks,
~S

I get this error when trying to send EOS from one account to another.  Can you help?

![image](https://user-images.githubusercontent.com/31561227/41816382-b7382e84-7738-11e8-886d-3e9da34be73c.png)

I think I found the issue.  Here is what I get when I try to vote.

![image](https://user-images.githubusercontent.com/31561227/41816397-628b0e8c-7739-11e8-94e8-e4d5befd3614.png)

However I can't stake my coins
![image](https://user-images.githubusercontent.com/31561227/41816419-d5dbb6ac-7739-11e8-8c00-3600ef1dfc4f.png)

I'm in a catch 22?

**Comment by aaroncox** [comment]
I’ll also address the other issues mentioned tomorrow, I think we have most of them working already. I didn’t see the full extent of your comments in the initial email from GitHub!

**Comment by controllinghand** [comment]
No worries.  I love the wallet.  A few suggestions:
1) This is more than a voter wallet so you might think about changing the name eos-voter?
2) As you can see from some of the errors above I didn't realize I needed to stake enough token in order to send.  So,  I'm not sure if you can check for the user before they try any of the functions like voting and sending EOS a head of time and pop up a warning that the need to stake for CPU and Bandwidth
3) Lastly it would be good if you can check for upper-case letters in account names so user knows that only lower-case works.  or force a routine to auto lower-case?

Thanks again.
~S

**Comment by aaroncox** [comment]
A few answers for ya, based on the previous comments. 

1. We are in the process of rebranding/renaming now, and having some art assets created.
2. It's a hard thing to nail down, because it depends on the usage on the entire network. We do see it as an issue though and are looking for ways to help notify users if their staked balance is too low (0.2.0 has warnings now if you try to unstake too much).
3. Good suggestion, we'll get that tied in to everywhere we allow username inputs.

If you ended up in a state with 0 staked in CPU/NET, you won't even be able to increase your stake, and will need another account to delegate some resources to fix the problem. It's a weird situation and some BPs have instructed people to set their stake to 0 (which we wouldn't recommend, since you can't do anything), so that's why we're now adding warnings on any actions that set the staked amount below 1.

**Comment by controllinghand** [comment]
Awesome.  Look forward to the version update.  Keep up the great work!
U rock!

**Comment by aaroncox** [comment]
The account name inputs are all lower case now - and I've opened issue #231 as a "catch all" for adding some sort of warnings to help guide users on resources within their account.

Closing this one out for housekeeping purposes!

**Comment by controllinghand** [comment]
U Rock!
