### ISSUE TITLE
"Private Key Does Not Match" Message For a Valid Key Pair

### ISSUE THREAD

**Issue by ThghtCrmnl** [greymass/eos-voter#227]
Hi,

I'm getting the "Private Key Does Not Match" message when I enter my private key, even though the public key I provided matches the expected public key. 
<img width="581" alt="capture" src="https://user-images.githubusercontent.com/41280689/42744727-ba6bdf70-88f8-11e8-9287-d2dd28f5499f.png">

This seems like a bug, but at the same time I haven't seen anyone else report the same issue, which kinda worries me. Any help would be greatly appreciated.

**Comment by acebaker** [comment]
I'm running into this as well. The keys that are displayed match, but EOS Voter is returning an error as if they don't match.

Wallet worked fine a few versions ago when I voted for initial block producers. Didn't use it for a few weeks after voting and when I updated to 0.2.2 this error appeared. Tried again with the latest version (0.3.3) and it's still happening.

Thanks!

**Comment by aaroncox** [comment]
Question for both of you - are you disconnecting from the internet to put in your keys? 

I've seen a rash of people recently doing this - and as of 0.3.3, our tool requires an internet connection to verify your key. 

Since so many people disconnect when entering it - we'll change that to allow disconnecting for input. Though really I'm not sure how effective a security measure it actually is.

**Comment by ThghtCrmnl** [comment]
Yes I do disconnect my internet connection. You may be right about the effectiveness of doing that, but I figured it can’t hurt, just in case there is some sort of a virus on my machine...

I will try it without disconnecting then.

Thanks!

On Jul 17, 2018, at 12:02 PM, Aaron Cox <notifications@github.com<mailto:notifications@github.com>> wrote:


Question for both of you - are you disconnecting from the internet to put in your keys?

I've seen a rash of people recently doing this - and as of 0.3.3, our tool requires an internet connection to verify your key.

Since so many people disconnect when entering it - we'll change that to allow disconnecting for input. Though really I'm not sure how effective a security measure it actually is.

**Comment by alexdimella** [comment]
@ThghtCrmnl I hope you were able to resolve your problem. I am in the same situation. Other's on Reddit are having issues as well.

Here are the order of events that got me here...

Mainnet launches
I downloaded greymass eos-voter app a few days later to vote. 
Created an account and got an account name, used my private key. 
Private key worked- All of my EOS was there and staked in wallet. 
When the vote was over, I then unstaked, waited over 3 days. 
Logged back into eos-voter app to check and everything was where it should be.
Also checked eosflare.io for my funds and that was looking correct as well, along with some airdrops.
Since I noticed the airdrops, I went to the wallet to add tokens BUT the version I had did not have that feature (to add a Token) so I had to download the latest version...

AND HERE IS WHERE THE PROBLEM STARTS...

![privatekeydoesnotmatch](https://user-images.githubusercontent.com/36021306/42967859-8c9e3876-8b6f-11e8-86eb-db5e7ab0884d.jpg)

After installing the new version of eos-voter, it refuses to take my EXACT SAME private key that was used before. I never changed it. I tried connected and disconnected. This has to be a bug or something!?

Here is my public key where you can see my funds. It's all there, all transactions reported perfectly...

https://eosflare.io/account/gu3tcnrxhege
EOS5e7o9VCJYo4hch5KxDA69Mh48J1KZFNUuDfSQ4f5n6DuHc8krh

I still have my ERC20 keys that I used to register my EOS pre-mainnet. 

What should be the next steps for us to take? Thank you for your time to read this. -Alex

**Comment by aaroncox** [comment]
@alexdimella - Your issue is different. Notice how the screenshot in the original issue above how the Public Keys in both the grey and red boxes are identical. Your screenshot shows non-matching keys, which means the private key actually doesn't match.

**Comment by alexdimella** [comment]
@aaroncox What should I do in my case? Its the same exact Private Key I used before. The only one I've ever had. I'll move this to another thread.

**Comment by aaroncox** [comment]
Just leaving this as a note for what we need to do to resolve this issue: during this part of the import process, the key validator should check to see if the account is already loaded in the internal caches, before it attempts to retrieve the account again while validating the key. This will allow users to "disconnect from the internet" while inputting their private keys.
