### ISSUE TITLE
Avast reports virus in 3.3

### ISSUE THREAD

**Issue by Auggie1** [greymass/eos-voter#246]
Avast is reporting threat Win32:Evo-gen is infecting the win-eos-voter-0.3.3.exe file on both Win7 and Win10 machines.

Thanks, Auggie

**Comment by ScottSallinen** [comment]
Actually, this isn't reporting a virus. Avast uses that term for "suspicious files", specifically those it hasn't seen often and isn't sure about. 

Rest assured, the program is safe!

As it is a false positive, if you don't mind, please mark it as such in Avast. That will help tell them it should not be suspicious!

**Comment by Auggie1** [comment]
OK, thanks...

**Comment by aaroncox** [comment]
It's something we're looking into (how better to compile the application so Avast doesn't freak out) - but closing this issue since it's not a concrete task for us to complete. In the end it'll end up being a long process of research and slow improvements so that virus scanners are more used to our application.
