### ISSUE TITLE
How can I unlock my wallet on startup?

### ISSUE THREAD

**Issue by kargakis** [greymass/eos-voter#272]
I am trying to create a new account on the EOS network and eos-voter asks me to unlock my wallet but I haven't set any password to unlock it in the first place. In general, I would love to see a stupid step-by-step guide to start using EOS with eos-voter.
![eos](https://user-images.githubusercontent.com/3900799/43361284-2ae3ffa4-92cb-11e8-9b08-f3de2ed5960c.png)

**Comment by aaroncox** [comment]
Did you click "Skip Import" to get to this point in the wallet without already importing a key?

**Comment by kargakis** [comment]
Yeah, that's what I did. It's unclear how can I import a key and create a hot wallet.

**Comment by kargakis** [comment]
Seems like a chicken and egg problem. If I don't "Skip Import", I am required to "Enter the public key or account name." which I assume needs to be registered already in the EOS network.

**Comment by jerrydv** [comment]
Same problem here.

**Comment by aaroncox** [comment]
Yeah - this is unfortunately how EOS works. An account is needed first, associated with a public/private key pair, in order to use the network to create additional accounts. It's not possible to use a Watch Wallet to create an initial account, you'll need to use an external service (outside of the wallet) to create that initial account. 

What you can do though is use our wallet to generate the two keypairs needed (active/owner), and use those in an external service to create the initial account. 

We do have a smart contract we're testing for account creation if you're interested in testing that out. It allows for account creation with a simple withdraw from an exchange with a specific memo. If you're interested in testing it out, feel free to [reach out on telegram](https://t.me/eoswalletgreymass) and we can walk you through the steps.

Going to close this one out - since it's not something we can resolve ourselves (it's an EOS network limitation).

**Comment by kargakis** [comment]
> Yeah - this is unfortunately how EOS works. An account is needed first, associated with a public/private key pair, in order to use the network to create additional accounts. It's not possible to use a Watch Wallet to create an initial account, you'll need to use an external service (outside of the wallet) to create that initial account.

How hard is it to add this functionality in eos-voter? The initial UX in EOS sucks big time and it would be nice to have a single tool that can bootstrap people into the network and handle common tasks like transactions.

**Comment by aaroncox** [comment]
We're planning on getting it added into the UX once we get a bit more testing done on the smart contract side. We have a lot of the actual UI already created and tried hard to get it included in the 0.4.0 build, but didn't want to delay 0.4.0 any longer so it got cut. 

The end goal is to have a new step in the setup process that covers the "I don't have an account yet" scenario, which either allows for:

- an "Account Creation Request Code" (string of username + public keys) which can be given to an existing account holder to create an account for you.
- a "Smart Contract Memo Code" (string, `username-ownerPublicKey-activePublicKey` format) that can be issued from an exchange with existing funds, and the smart contract will automatically create the account.

**Comment by kargakis** [comment]
Sounds great, thanks!
