### ISSUE TITLE
Need web portal

### ISSUE THREAD

**Issue by masterkrang** [greymass/eos-voter#28]
I'm happy to build a web page that shows this tool, something basic with info. I think this is a project worth showing who built it and why, to have a more secure feeling.

**Comment by aaroncox** [comment]
We're trying to come up with a more permanent name right now - which will hopefully lead into branding and then website creation. 

I'd invite ya to join our telegram group if you're not already - https://t.me/eoswalletgreymass

I'm going to close this issue out since it's external to the app itself, but we're aware of the need and definitely need a website for the app itself.
