### ISSUE TITLE
armhf (rpi3/raspbian) version

### ISSUE THREAD

**Issue by jeee** [greymass/eos-voter#345]
Would love to see a release that runs on raspbian on the raspberry pi3

**Comment by ScottSallinen** [comment]
Interestingly enough, with a bit of effort it is indeed possible to compile the wallet for the Raspberry Pi :smile: 
I tried this early on, and it does work (albiet very slowly). 

A release for it is a bit hard though, since it requires some tweaking and can't be built during the general purpose release builder. I'll take a look again to see if its possible to package up the custom build as something portable, though!

**Comment by jeee** [comment]
Be nice if it goes smoother but I managed to install the existing arm package:
`dpkg --add-architecture armv7l`
Get the dependencies (in the depends section of dpkg -I linux-eos-voter-0.5.3-armv7l.deb):
```
apt --print-uris --yes install gconf2 gconf-service libnotify4 libappindicator1 libxtst6 libnss3 libxss1 |grep ^\' |cut -d\' -f2 > packagelist.txt
wget --input-file packagelist.txt
```
install dependencies:
`dpkg -i *.dep`
Get the eos-voter and install it:
`dpkg -i --ignore-depends=libnotify4,libappindicator1,libxtst6,libnss3,libxss1  linux-eos-voter-0.5.3-armv7l.deb`
it gives me a warning but I was still able to run it by running /opt/eos-voter/eos-voter.

**Comment by aaroncox** [comment]
Going to close this as a non-issue for now, but awesome that you got it running. We will have to at some point provide documentation on our upcoming website with how to do this.

**Comment by jeee** [comment]
I just tried the new version (both 6.1 and 6.2, 6.0 does not have a armv7l version) and that only shows 'loading' but nothing happens. (in terminal it shows [info] manager: 'loaded').
