### ISSUE TITLE
Signing new active key with owner

### ISSUE THREAD

**Issue by plouto5** [greymass/eos-voter#378]
Trying to change the active key with a watch wallet and signing with the cold wallet. I did it once before to my ledger nano s. Now I want to change it to a scatter key so I can use it with dapps. 

Using current version 0.5.3

`Error                                                                                                                                                                                                     500,"message"."Internal Service Error","error".{"code".3090003,"name"."unsatisfied_authorization","what"."Provided keys, permissions, and delays do not satisfy declared 
authorizations","details".[{"message"."transaction declares authority '{\"actor\".\"{acountname}\",\"permission\".\"active\"}', but does not have signatures for it under a provided delay 
of 0 ms, provided permissions [], provided keys [\"EOSxxxxxxxxxxxxxxxxx\"], and a delay max limit of 
3888000000ms","file"."authorization_manager.cpp","line_number".413,"method"."check_authorization"}]}}`

**Comment by aaroncox** [comment]
Does the cold wallet still have the owner key in it? 

If so - I think we have this fixed in the next build, but will double check. If you're comfortable editing the transaction manually: 
- generate the *unsigned* transaction with the watch wallet
- edit the unsigned transaction file with a text editor
- do a search for "permission" in that file, and it will likely have a value of `active`. 
- change that value to `owner` and save the file
- continue as normal signing with cold wallet/etc

That's the immediate fix if you wanted to sign that transaction today.

**Comment by plouto5** [comment]
Thank you will give this a shot tomorrow! And yes the cold wallet has the owner keys. I will report back with my results.

**Comment by plouto5** [comment]
It worked!! Thanks for the help for what ever reason current version has the permission to "active",

Thanks for the solution.

**Comment by aaroncox** [comment]
Fantastic! 

I've been testing this today in the newest version and can confirm we'll have it resolved in the next release.
