### ISSUE TITLE
"symbol" in created unsigned Smart Contracts transaction was not correct.

### ISSUE THREAD

**Issue by empyre** [greymass/eos-voter#382]
![1](https://user-images.githubusercontent.com/523868/46901812-1ea3ff00-ce80-11e8-8f3b-3f0734d06102.png)
![2](https://user-images.githubusercontent.com/523868/46901815-2368b300-ce80-11e8-9411-3632821eae2a.png)
When using the "Smart Contracts" in "Wallet Tools", the precision for the symbol was lost in the created transaction. So the cold wallet cannot sign the transaction.
V0.5.3

**Comment by empyre** [comment]
@aaroncox Have already tried this, the same result.

**Comment by aaroncox** [comment]
Alright interesting, I'll have to dig more into the contract and see if I can successfully get a transaction working myself. Do you happen to have any links or places I can dig up more information about this contract and it's actions?

**Comment by empyre** [comment]
@aaroncox For any contract that using the symbol fields, the created transaction missing the precision part.
You may try any contract using the eosio.token code.

**Comment by aaroncox** [comment]
Yeah I'm noticing this as well after doing a bit of debugging today.

eos-voter isn't actually manipulating that string at all before being passed to eosjs, and it seems eosjs is actually what is stripping out the portion of the string. For example:

- `4,INF` when passed via `eos.transaction(op)` is stripped down to `INF`
- `0.0000 INF` when passed via `eos.transaction(op)` is stripped down to `INF`

I'm going to have to dig into eosjs some more and potentially open an issue on their end to figure out why it's stripping that down. I'm assuming that the `symbol` type is just expecting the actual symbol and is attempting to convert it to that.

**Comment by empyre** [comment]
@aaroncox How about pass the plain string to the transaction? Go through eosjs may not be necessary.
Or at least give an option to the user to choose from.

**Comment by aaroncox** [comment]
It's unfortunately a plain string as it's passed in:

![image](https://user-images.githubusercontent.com/677686/46910268-73db2180-cf0f-11e8-8a9c-4bc1f124d551.png)

https://github.com/greymass/eos-voter/blob/master/app/shared/actions/transaction.js#L36-L41

This process is what builds the actual eosjs transaction which can then be signed. I think the eosjs format utility that's altering the value: 

https://github.com/EOSIO/eosjs/blob/v16.0.9/docs/format.md#parseasset--object

It's detecting the type of `symbol` and then reducing it down to it's symbol here:

https://github.com/EOSIO/eosjs/blob/v16.0.9/src/format.js#L290-L321

**Comment by aaroncox** [comment]
We are going to need to upgrade to EOSJS V20 or beyond to get this resolved. We didn't have time to make it into this release, since it requires rewriting all of our transaction logic, but are planning for one of the next releases to make that jump.

**Comment by empyre** [comment]
@aaroncox Thanks for your update. This is awesome.

**Comment by znebby** [comment]
@aaroncox I don't understand why you need to upgrade to eosjs2. https://eostoolkit.io/ is on eosjs1 and they managed to do the airgrab just fine.

**Comment by aaroncox** [comment]
I'll look at how they're building the transaction, maybe there's a way to have it generated while avoiding this issue all together. 

Right now it's the formatters in eosjs, which use the ABI to decorate the values, that's causing the problem. It's possible they aren't using those decorators, where we need to in order to offer offline signing of transactions.

**Comment by aaroncox** [comment]
Alright, I did some investigation, and eostoolkit just assembles the data and Scatter is what's actually building the transaction. Scatter does in fact use eosjs2, so the formatters that are impacting our transaction building aren't currently affecting Scatter apps (like eostoolkit). 

The reason the formatters are firing on this field is because in the ABI it's set as a `symbol` type, and `symbol` in eosjs v1 is a simple symbol (string) with no precision information. From directly in the eosjs v1 code:

```
/**
  Internal: precision, symbol
  External: symbol
  @example 'SYS'
*/
```

It intentionally strips out the `4,` from `4,INF`, since the formatters themselves are only expecting the actual symbol. If the infinicoinio contract used the `asset` struct type instead of `symbol`, `0.0000 INF` (and potentially `4,INF`) would end up working.

I tried 3 different methods of assembling the transaction this afternoon in an attempt to bypass the formatters, but none of them actually passed `4,INF`, and the formatters themselves reduced them all to `INF`.

**Comment by aaroncox** [comment]
Alright, 3rd update.

After talking with @nsjames about the issue, he pointed me in a direction that actually can solve this issue. 

The `eos.transaction()` method eos-voter is currently using apparently applies these formatters differently than `eos.contract()`. I have no idea why, and it'll probably never be fixed (due to v2), so I am planning on rewriting our arbitrary transaction signer to use `eos.contract()` (since we don't do batching in there) and that should resolve the issue without the need for a eosjs v2 update.

We are planning a 0.6.1 release in the near future to resolve some minor bugs with the newest release, we'll have this change also bundled up and released at the same time.

**Comment by znebby** [comment]
NSJames to the rescue! Awesome, looking forward to it!
