### ISSUE TITLE
Not allowed to load local resource Issue

### ISSUE THREAD

**Issue by oyosc** [greymass/eos-voter#433]
os: mac 10.13.1
When i run the cmd: 
`npm run start`
Then the google developer tools show the error message:
`Not allowed to load local resource Issue`
And i try all methods according to the [link](https://github.com/electron/electron/issues/5107),but not work.
Finally,i see the doc of electron, and change the code
`  ui.loadURL(`file://${path.join(resourcePath, 'renderer/basic/index.html')}#${route}`);
`
to:
` ui.loadURL(`file://${__dirname}/renderer/basic/index.html#${route}`);`
Next is ok. so maybe you code have some problem? when in development envirmoent ,you code is okay,but in the production envirmoent, it will show the above error message

**Comment by aaroncox** [comment]
Does this show in the console of the production build? I don't see it 🤔

**Comment by aaroncox** [comment]
Sorry for the long delay on this.

I think we might end up just removing `npm run start`, because the reason it's failing is due to webpack not properly being executed during that process. 

For development purposes, `npm run dev` accomplishes everything that start normally would, including the missing webpack issues that `npm run start` is suffering from.
