### ISSUE TITLE
Error e.decorateAppAPIMethods is not a function

### ISSUE THREAD

**Issue by trempao** [greymass/eos-voter#756]
When trying to unstake eos tokens using greymass eos voter tool I get this error.

Thanks in advance

**Comment by aaroncox** [comment]
This error happens when it cannot communicate with a Ledger. I'm assuming your account is tied to a Ledger? 

Some things to try:

- Close all the apps you have that use your Ledger. If you have Scatter or Ledger Live open, one of those apps might be monopolizing the connection to the device preventing it from working. 
- Use the USB icon in the upper right to stop/start the Ledger service, sometimes this kicks the connection back in. 
- Last resorts are unplugging and plugging the device back in, and potentially restarting eos-voter.

One question: which operating system are you using?

**Comment by trempao** [comment]
Hi Aaron
Thanks so much for your help and sorry for the late reply. Actually I am using windows 7. I am getting a different error trying to unstake my eos tokens: 


thanks!!  :-)   

billed CPU time (1769 us) is greater than the maximum billable CPU time for the transaction (13 us)

{
"code":500
"message":"Internal Service Error"
"error":{
"code":3080004
"name":"tx_cpu_usage_exceeded"
"what":"Transaction exceeded the current CPU usage limit imposed on the transaction"
"details":[...]
}

**Comment by aaroncox** [comment]
This new error is different than the first, and is stating you wouldn't have enough CPU after unstaking to perform the transaction.
